version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-toastify
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: parse-torrent
    versions:
    - 9.1.1
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: electron-devtools-installer
    versions:
    - 3.1.1
